### ISSUE TITLE
no backpropagation for netLBP?

### ISSUE THREAD

**Issue by vinits5** [HighwayWu/ImageInpainting#5]
While going through the code, I found that `netLBP`'s parameters are not getting updated as the `optimizerLBP.step()` function is not called anywhere in `model.py` file.

https://github.com/HighwayWu/ImageInpainting/blob/master/model.py#L268
I believe that the above link indicates the function that optimizes parameters of netG, netD, netD2 but it does not update netLBP. Can you please point me to the correct location where the optimizer for LBP is calling the step function? Thank you.

**Comment by HighwayWu** [comment]
Hi, Vinits.

Actually, this script is for training the second stage of the model, i.e., the image inpainting network. In this stage, I assume that the netLBP is already trained, so I remove the optimizerLBP. If you want to retrain the whole model, it would be better to train the netLBP as first; otherwise, you may add the step of optimizerLBP to form an end-to-end training.

Best,
Haiwei
